### Part A

In [1]:
# HERE YOU WILL WRITE CODE TO TEST A NUMBER OF PREDICTORS
# AND FINALLY CHOOSE AND TRAIN THE PREDICTOR THAT YOU WILL BE USING FOR PART B

In [2]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import numpy as np

## IMPORT DATA

In [3]:
df = pd.read_csv('CE802_P2_Data.csv')
df

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F13,F14,F15,F16,F17,F18,F19,F20,F21,Class
0,-0.123210,2577.3200,2183.52,7747.32,2.16,9693.21,-2.24980,-1381.98,3033.55,53.796,...,6.7860,1,-3.9290,-0.8095,3.5800,-5.9384,-9.3420,1,NaN,True
1,-2.064600,1200.1200,1654.74,6027.72,2.16,9391.26,-2.74200,-1336.20,2081.35,33.514,...,5.5240,0,-1.6609,-2.3020,3.8880,-6.5640,-6.3806,1,NaN,False
2,-0.083748,2769.3500,2661.42,7798.66,2.16,9296.28,-3.21300,-1531.16,3397.15,39.430,...,10.0870,0,-2.5100,-2.8190,2.1606,-5.2340,-9.6780,0,NaN,False
3,-2.808300,3161.5200,2199.12,8369.32,5.16,7990.71,-2.27030,-1397.03,3289.99,42.012,...,15.5400,1,-2.2555,-0.9770,8.2160,-5.8166,-6.1512,0,42.06,True
4,-0.445800,2707.4200,2083.62,9054.72,5.16,8691.81,-3.73100,-804.04,1903.35,43.172,...,4.5188,0,-1.7843,-1.3690,0.7562,-6.4060,-9.5320,0,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,-0.637200,2575.9200,1493.97,7726.38,2.16,8822.31,-2.27120,-1052.44,2790.55,56.832,...,5.8160,0,-2.0949,-1.9290,1.3156,-6.3420,-6.9018,1,32.58,False
996,-0.062512,2713.8200,1484.64,7529.12,2.16,9395.07,-2.43980,-1279.56,3143.73,49.938,...,13.6120,1,-1.6278,-0.5306,0.7642,-6.1828,-8.1960,1,NaN,False
997,-0.458100,2827.8675,1539.30,7463.92,5.16,9285.81,-2.71500,-1503.12,3497.55,20.112,...,5.0459,0,-1.8705,-2.7190,2.2880,-5.9302,-8.0580,1,33.81,False
998,-0.323700,2681.1200,2399.52,8268.92,2.16,10062.51,-2.79400,-1387.82,3001.85,32.880,...,7.8240,1,-3.1360,-0.9401,4.0980,-5.7562,-12.4580,0,35.79,True
999,-2.061000,4034.1200,1041.12,9405.32,5.16,8583.51,-1.64566,-1311.16,3986.95,29.592,...,7.8380,0,-1.8624,-1.8080,1.5582,-4.6114,-6.1788,0,37.80,True

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   F1      1000 non-null   float64
 1   F2      1000 non-null   float64
 2   F3      1000 non-null   float64
 3   F4      1000 non-null   float64
 4   F5      1000 non-null   float64
 5   F6      1000 non-null   float64
 6   F7      1000 non-null   float64
 7   F8      1000 non-null   float64
 8   F9      1000 non-null   float64
 9   F10     1000 non-null   float64
 10  F11     1000 non-null   float64
 11  F12     1000 non-null   float64
 12  F13     1000 non-null   float64
 13  F14     1000 non-null   int64
 14  F15     1000 non-null   float64
 15  F16     1000 non-null   float64
 16  F17     1000 non-null   float64
 17  F18     1000 non-null   float64
 18  F19     1000 non-null   float64
 19  F20     1000 non-null   int64
 20  F21     500 non-null    float64
 21  Class   1000 non-null   bool
dtypes: bool(1), float64(19), int64(2)
memory usage: 165.2 KB

In [5]:
def train_model(data: pd.DataFrame = None, 
                fill_strategy: str = None,
                model: str = None):
    """Trains a model on the given data and returns performance metrics.
    
    Parameters:
    data (pd.DataFrame): The data to use for training.
    fill_strategy (str): The strategy to use for filling missing values.
    model (str): The name of the model.
    
    Returns:
    dict: A dictionary containing the model name, fill strategy, and performance metrics.
    """
    
    # Fill missing values in the F21 column using the specified strategy
    if fill_strategy=='mean':
        data['F21'] = df['F21'].fillna(data['F21'].mean())
    elif fill_strategy=='mode':
        data['F21'] = df['F21'].fillna(data['F21'].mode()[0])
    elif fill_strategy=='median':
        data['F21'] = df['F21'].fillna(data['F21'].median())
    elif fill_strategy=='remove':
        data = data.drop('F21', axis=1)
    
    # Split the data into features and labels
    features = data.drop('Class', axis=1)
    labels = data['Class']

    # Split the data into training and test sets
    X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.1, random_state=428969)

    # Create a decision tree classifier
    dtc = DecisionTreeClassifier(random_state=42, max_depth=500)

    # Fit the classifier to the training data
    dtc.fit(X_train, y_train)

    # Make predictions on the test data
    pred = dtc.predict(X_test)
    
    # Make predictions on the training data
    pred_train = dtc.predict(X_train)
    
    # Calculate performance metrics for the training data
    train_accuracy = accuracy_score(y_train, pred_train)
    
    # Calculate performance metrics for the test data
    accuracy = accuracy_score(y_test, pred)

    # Return the model name, fill strategy, and performance metrics
    return {'Model': model,
            'Strategy': 'None' if fill_strategy == 'remove' else fill_strategy, 
            'Train Accuracy': train_accuracy,
            'Accuracy': accuracy}

In [6]:
without_column = train_model(model='DecisionTreeClassifier',
                             data=df,
                             fill_strategy='remove'
                             )

with_mean = train_model(model='DecisionTreeClassifier',
                             data=df,
                             fill_strategy='mean')

with_median = train_model(model='DecisionTreeClassifier',
                             data=df,
                             fill_strategy='median')

with_mode = train_model(model='DecisionTreeClassifier',
                             data=df,
                             fill_strategy='mode')

In [7]:
# Without the F21 column
without_column

{'Model': 'DecisionTreeClassifier',
 'Strategy': 'None',
 'Train Accuracy': 1.0,
 'Accuracy': 0.86}

In [8]:
# Using mean as a fill strategy
with_mean

{'Model': 'DecisionTreeClassifier',
 'Strategy': 'mean',
 'Train Accuracy': 1.0,
 'Accuracy': 0.83}

In [9]:
# Using median as a fill strategy
with_median

{'Model': 'DecisionTreeClassifier',
 'Strategy': 'median',
 'Train Accuracy': 1.0,
 'Accuracy': 0.83}

In [10]:
# Using mode as a fill strategy
with_mode

{'Model': 'DecisionTreeClassifier',
 'Strategy': 'mode',
 'Train Accuracy': 1.0,
 'Accuracy': 0.83}

In [11]:
joint_dict = {'Model': [], 'Strategy': [], 'Train Accuracy': [], 'Accuracy': []}
dict_list = [without_column, with_mean, with_median, with_mode]

for i in dict_list:
    for key, value in i.items():
        joint_dict[key].append(value)

In [12]:
pd.DataFrame(joint_dict)

                    Model Strategy  Train Accuracy  Accuracy
0  DecisionTreeClassifier     None             1.0      0.86
1  DecisionTreeClassifier     mean             1.0      0.83
2  DecisionTreeClassifier   median             1.0      0.83
3  DecisionTreeClassifier     mode             1.0      0.83

In [17]:
def train_more_models(data: pd.DataFrame = df,
                      test_size: int = None
                      ):
    """Trains multiple models on the given data and returns their performance scores.
    
    Parameters:
    data (pd.DataFrame): The data to use for training.
    
    Returns:
    pd.DataFrame: A dataframe containing the performance scores for each model.
    """
    
    # Define a dictionary of models to train
    model_list = {'decision-tree': DecisionTreeClassifier(), 
                  'logistic-regression': LogisticRegression(max_iter=1000, solver='liblinear'), 
                  'gradient-boosting': GradientBoostingClassifier(subsample=0.5, n_estimators=1000), 
                  'random-forest': RandomForestClassifier(),
                  'ada-boost': AdaBoostClassifier(),
                  'svc': SVC(kernel='linear')}
    
    # Split the data into features and labels
    features = data.drop(['F21', 'Class'], axis=1)
    labels = data['Class']

    # Split the data into training and test sets
    X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=test_size, random_state=42)
    
    # Initialize a dictionary to store the model results
    model_results = {}
    
    # Train each model and store their performance scores
    for model_name, model in model_list.items():
        model.fit(X_train, y_train)
        
        # Make predictions on the training and test data
        pred_train = model.predict(X_train)
        pred = model.predict(X_test)
        
        # Calculate the accuracy scores for the training and test data
        accuracy_train = accuracy_score(pred_train, y_train)
        accuracy_test = accuracy_score(pred, y_test)
        
        # Add the accuracy scores to the model results dictionary
        model_results.update({model_name: [accuracy_train, accuracy_test]})
    
    # Convert the model results to a dataframe and rename the rows
    model_results = pd.DataFrame(model_results)
    model_results = model_results.rename(index={0: 'train_score', 1: 'test_score'})
        
    return model_results

In [18]:
# Training with 80% of the samples
models_80 = train_more_models(test_size=0.2)
print('Sample size = 80%')
models_80

Sample size = 80%

,decision-tree,logistic-regression,gradient-boosting,random-forest,ada-boost,svc
train_score,1.00,0.67875,1.000,1.00,0.82375,0.6725
test_score,0.77,0.68500,0.805,0.85,0.72500,0.6800

In [19]:
# Training with 90% of the samples
models_01 = train_more_models(test_size=0.1)
print('Sample size = 90%')
models_01

Sample size = 90%

,decision-tree,logistic-regression,gradient-boosting,random-forest,ada-boost,svc
train_score,1.00,0.703333,1.00,1.00,0.813333,0.68
test_score,0.91,0.680000,0.84,0.86,0.700000,0.64

Training using 90% of the data returned an accuracy of 91% hence I'll be using DecisionTreeClassifier

In [22]:
features = df.drop(['F21', 'Class'], axis=1)
labels = df['Class']

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.1, random_state=42)

model_ = DecisionTreeClassifier()

model_.fit(X_train, y_train)

# Make predictions on the training and test data
pred_train = model_.predict(X_train)
pred = model_.predict(X_test)

# Calculate the accuracy scores for the training and test data
accuracy_train = accuracy_score(pred_train, y_train)
accuracy_test = accuracy_score(pred, y_test)

print('train: ', accuracy_train)
print('test: ', accuracy_test)

train:  1.0
test:  0.93

### Part B

In [23]:
# HERE YOU WILL USE THIS TEMPLATE TO SAVE THE PREDICTIONS ON THE TEST SET

# Load the test data
test_df = pd.read_csv('CE802_P2_Test.csv')

# Make sure you work on a copy
test_data = test_df.iloc[:,:-1].copy()

test_data = test_data.drop('F21', axis=1)

predicted = model_.predict(test_data)

# Replace the last (empty) column with your prediction
test_df.iloc[:,-1] = predicted

# Save to the destination file
test_df.to_csv('CE802_P2_Test_Predictions.csv', index=False, float_format='%.8g')

# IMPORTANT!! Make sure only the last column has changed
assert pd.read_csv('CE802_P2_Test.csv').iloc[:,:-1].equals(pd.read_csv('CE802_P2_Test_Predictions.csv').iloc[:,:-1])